#!/bin/sh
set -eu

# This service runs on boot to work around issues relating to LXD and snapd.

# Workaround for https://github.com/conjure-up/conjure-up/issues/1448
(set +e
  echo "applying snapd apparmor profiles"
  apparmor_parser /var/lib/snapd/apparmor/profiles/*
  echo "apparmor_parser: exit status $?"
)

# Workaround for https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/357
services="{{services}}"

deadline="$(expr "$(date +%s)" + 600)"

while [ "$(date +%s)" -lt "$deadline" ]; do
  for service in $services; do
    echo "$service: checking"
    if ! systemctl is-active "$service"; then
      echo "$service: not active, restarting"
      systemctl restart "$service" || true
    fi
  done

  sleep 10
done

echo "deadline has passed, exiting gracefully"
